apiVersion: v1
kind: Service
metadata:
  name: datanode
  labels:
    app: datanode
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: datanode
---
  apiVersion: apps/v1beta1
  kind: StatefulSet
  metadata:
    name: datanode
  spec:
    serviceName: datanode
    replicas: 1
    template:
      metadata:
        labels:
          app: datanode
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "28942"
      spec:
        containers:
          - name: datanode
            image: flokkr/hadoop-hdfs-datanode:ozone
            env:
              - name: PROMETHEUSJMX_ENABLED
                value: "true"
              - name: PROMETHEUSJMX_AGENTOPTS
                value: port=28942
            volumeMounts:
              - name: config
                mountPath: "/opt/hadoop/etc/hadoop"
                readOnly: true
        volumes:
          - name: config
            configMap:
              name: hadoopconf
