apiVersion: v1
kind: Service
metadata:
  name: ksm
  labels:
    app: ksm
spec:
  ports:
  - port: 9874
    name: web
  clusterIP: None
  selector:
     app: ksm
---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: ksm
spec:
  serviceName: ksm
  replicas: 1
  template:
    metadata:
      labels:
        app: ksm
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "28942"
    spec:
      containers:
        - name: ksm
          image: flokkr/hadoop:ozone
          args: ["hdfs","ksm"]
          env:
            - name: PROMETHEUSJMX_ENABLED
              value: "true"
            - name: PROMETHEUSJMX_AGENTOPTS
              value: port=28942            
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf
