apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: namenode
  namespace: hadoop
spec:
  serviceName: namenode
  replicas: 1
  template:
    metadata:
      labels:
        app: namenode
    spec:
      containers:
        - name: namenode
          image: elek/hadoop-hdfs-namenode:latest
          env:
            - name: ENSURE_NAMENODE_DIR
              value: /data/namenode
          volumeMounts:
            - name: config
              mountPath: "/opt/hadoop/etc/hadoop"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: hadoopconf 
